/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppGuidesRouteImport } from './routes/_app.guides'
import { Route as AppHiddenRouteImport } from './routes/_app.hidden'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppNotoficationsRouteImport } from './routes/_app.notofications'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppGuidesIdRouteImport } from './routes/_app.guides.$id'
import { Route as AppOpportunitiesIdRouteImport } from './routes/_app.opportunities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesRoute = AppGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AppRoute,
} as any)
const AppHiddenRoute = AppHiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppNotoficationsRoute = AppNotoficationsRouteImport.update({
  id: '/notofications',
  path: '/notofications',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesIdRoute = AppGuidesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGuidesRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/guides': typeof AppGuidesRouteWithChildren
  '/hidden': typeof AppHiddenRoute
  '/me': typeof AppMeRoute
  '/notofications': typeof AppNotoficationsRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/guides/$id': typeof AppGuidesIdRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/guides': typeof AppGuidesRouteWithChildren
  '/hidden': typeof AppHiddenRoute
  '/me': typeof AppMeRoute
  '/notofications': typeof AppNotoficationsRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/guides/$id': typeof AppGuidesIdRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/guides': typeof AppGuidesRouteWithChildren
  '/_app/hidden': typeof AppHiddenRoute
  '/_app/me': typeof AppMeRoute
  '/_app/notofications': typeof AppNotoficationsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/guides/$id': typeof AppGuidesIdRoute
  '/_app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/discover'
    | '/feed'
    | '/guides'
    | '/hidden'
    | '/me'
    | '/notofications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/sources'
    | '/guides/$id'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/discover'
    | '/feed'
    | '/guides'
    | '/hidden'
    | '/me'
    | '/notofications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/sources'
    | '/guides/$id'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/discover'
    | '/_app/feed'
    | '/_app/guides'
    | '/_app/hidden'
    | '/_app/me'
    | '/_app/notofications'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/guides/$id'
    | '/_app/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides': {
      id: '/_app/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof AppGuidesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hidden': {
      id: '/_app/hidden'
      path: '/hidden'
      fullPath: '/hidden'
      preLoaderRoute: typeof AppHiddenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notofications': {
      id: '/_app/notofications'
      path: '/notofications'
      fullPath: '/notofications'
      preLoaderRoute: typeof AppNotoficationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides/$id': {
      id: '/_app/guides/$id'
      path: '/$id'
      fullPath: '/guides/$id'
      preLoaderRoute: typeof AppGuidesIdRouteImport
      parentRoute: typeof AppGuidesRoute
    }
    '/_app/opportunities/$id': {
      id: '/_app/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppGuidesRouteChildren {
  AppGuidesIdRoute: typeof AppGuidesIdRoute
}

const AppGuidesRouteChildren: AppGuidesRouteChildren = {
  AppGuidesIdRoute: AppGuidesIdRoute,
}

const AppGuidesRouteWithChildren = AppGuidesRoute._addFileChildren(
  AppGuidesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGuidesRoute: typeof AppGuidesRouteWithChildren
  AppHiddenRoute: typeof AppHiddenRoute
  AppMeRoute: typeof AppMeRoute
  AppNotoficationsRoute: typeof AppNotoficationsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFeedRoute: AppFeedRoute,
  AppGuidesRoute: AppGuidesRouteWithChildren,
  AppHiddenRoute: AppHiddenRoute,
  AppMeRoute: AppMeRoute,
  AppNotoficationsRoute: AppNotoficationsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
